image: docker:stable

services:
    - docker:dind

variables:
    DOCKER_HOST: tcp://docker:2375

before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker info

stages:
    - build
    - test
    - deploy

build:
    stage: build
    script:
        - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME || true
        - docker build --cache-from $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME .
        - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
        - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    tags:
        - docker

test:
    stage: test
    script:
        - echo test
    tags:
        - docker

deploy:
    stage: deploy
    script:
        - echo deploy
    tags:
        - docker
    only:
        - production
